### PR TITLE
Added the architecture design  for distributor

### PR DESCRIPTION
**Pull request by jshaofuturewei**
As title

### CODE REVIEW

**Review by CoderKevinZhang — APPROVED** [review]

**Review by kimeunju108 — APPROVED** [review]
The new picture looks clear.

**Comment by cathyhongzhang** [comment]
Let's discuss this diagram in next Monday's meeting and then merge it. Thank you.

**Comment by cathyhongzhang** [comment]
Let's hold on the merge and discuss this design in next Monday's meeting.

**Comment by cathyhongzhang** [comment]
LGTM

**Pull request merged**
