### PR TITLE
Remove unnecessary priorities

### PR DESCRIPTION
**Pull request by kimeunju108**
What type of PR is this?

/kind cleanup

What this PR does / why we need it:
- This PR removed global scheduler's 9 priorities and their related logics and dependencies including selector_spreading.go, taint_toleration.go, interpod_affinity.go, node_prefer_avoid_pods.go, node_affinity.go, node_label.go, image_locality.go, most_requested.go, and resource_limits.go
- This PR performed bazel-testing, integration testing, and sanity testing.

Which issue(s) this PR fixes: 

Fixes #

Special notes for your reviewer:

Does this PR introduce a user-facing change?:

NONE

### CODE REVIEW

**Comment by yxiong2020** [comment]
Added it to Winter Release (Milestone #1)

**Review by cathyhongzhang — APPROVED** [review]
LGTM

**Comment by cathyhongzhang** [comment]
> Added it to Winter Release (Milestone #1)

Already add it to Milestone #1 (please refer to PR 18)

**Review by CoderKevinZhang — APPROVED** [review]
No problems from me. Feel free to merge

**Pull request merged**
