### PR TITLE
replace existing K8S Scheduler with the new light-weight scheduler wi…

### PR DESCRIPTION
**Pull request by nkwangjun**
…th plugins framework work with schedule api

**What type of PR is this?**
> Uncomment only one ` /kind <>` line, hit enter to put that in a new line, and remove leading whitespaces from that line:
>
> /kind api-change
> /kind bug
> /kind cleanup
> /kind design
> /kind documentation
> /kind failing-test
> /kind feature
> /kind flake

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

**Does this PR introduce a user-facing change?**:

```release-note

```

### CODE REVIEW

**Comment by nkwangjun** [comment]
@cathyhongzhang can you add other reviews for this commit please

**Comment by cathyhongzhang** [comment]
I have added other members and myself as reviewers. But since the code changes are huge, could you add some high level explanation about the code logic, such as the scheduling code flow, the algorithm implemented by this code, what predicates and priority functions are used so that it is easier for us to review the codes? Also could you make sure the CI tests that are associated with the part of K8S scheduler codes that you kept are passed? Thanks

**Comment by nkwangjun** [comment]
There are so many dependencies for original k8s schedulers modules and they are already deleted in the new light scheduler，for example kubernetes/pkg/kubelet、kubernetes/plugins. And I
 cannot delete these no used modules easily. 
Because the new scheduler module is light, and can run independently currently, so I decide to move it to kubernetes/globalscheduler , without any change for original k8s scheduler currently.

**Comment by nkwangjun** [comment]
There pr will be closed and I will  make another pr for the new scheduler, thanks.

**Comment by nkwangjun** [comment]
New pr is this: pr #81

**Comment by nkwangjun** [comment]
this pr will be closed， to a new pr #81 , thanks

**Pull request closed without merging**
